#!/bin/bash


dirname="${0%/*}"

main_yml=$(cat .package.d/lint.yml) || exit 1
prettier_yml=$(cat "$dirname"/prettier.yml) || exit 1

idents=($(printf "%s" "${prettier_yml}" |
             egrep -o '\{\{.[a-z]+(-[a-z]+)*(.[a-z]+(-[a-z]+)*)*\}\}' |
             sort -u |
             tr -d '{}'))
for ident in "${idents[@]}"; do
    value=$(printf "%s" "$main_yml" | yq -e "$ident" ) || exit 1
    prettier_yml=$(printf "%s" "${prettier_yml}" | sed -r "s/\{\{$ident\}\}/$value/g")
done
{
    printf "%s\n" "${prettier_yml}"
} > .prettierrc
